# Shared configuration for all services
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playstore_db?useSSL=false&serverTimezone=Asia/Kolkata
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  cloud:
    config:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.playstore: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

---
# User Service specific configuration
spring:
  config:
    activate:
      on-profile: user-service
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/playstore_user_db?useSSL=false&serverTimezone=Asia/Kolkata
  jpa:
    hibernate:
      ddl-auto: create

---
# Owner Service specific configuration  
spring:
  config:
    activate:
      on-profile: owner-service
  application:
    name: owner-service
  datasource:
    url: jdbc:mysql://localhost:3306/playstore_owner_db?useSSL=false&serverTimezone=Asia/Kolkata
  jpa:
    hibernate:
      ddl-auto: create

---
# Notification Service specific configuration
spring:
  config:
    activate:
      on-profile: notification-service
  application:
    name: notification-service

---
# API Gateway specific configuration
spring:
  config:
    activate:
      on-profile: api-gateway
  application:
    name: cloud-api-gateway
