# Shared configuration for all services
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      uri: http://localhost:9196

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: playStoreSecretKey2023ThisIsAVeryLongSecretKeyForJWT
  expiration: 86400000

logging:
  level:
    com.playstore: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
